site_name: Portfolio de José Serrahima Ezquerro
repo_url: https://gitlab.com/jose-serrahima/portfolio
repo_name: Portfolio
theme:
  language: es
  locale: es
  logo: images/2.jpeg
  name: material
  #name: readthedocs
  palette:
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/lightbulb 
        name: Cambiar a oscuro
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Cambiar a luminoso
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
plugins:
  - search:
      lang: es
markdown_extensions:
  - footnotes
#extra:
#  alternate:
#    - name: Castellano
#      link: /es
#      lang: es
#    - name: English
#      link: /en
#      lang: en
extra_css:
  - stylesheets/extra.css